import { defaultLocale, type Locale } from '../config/site';

type VoteLabels = {
  eyebrow: string;
  heading: string;
  copy: string;
  profile: string;
  guest: string;
  changeName: string;
  shareVotes: string;
  tabsLabel: string;
  selectedShow: string;
  votedSongs: string;
  saveStatus: string;
  localSaved: string;
  onlineSaved: string;
  saving: string;
  missingName: string;
  closed: string;
  comingSoon: string;
  pending: string;
  nameTitle: string;
  nameCopy: string;
  nameLabel: string;
  saveName: string;
  votesEyebrow: string;
  votesTitle: string;
  closeSettings: string;
  exportVotes: string;
  importVotes: string;
  deleteVotes: string;
  noSongs: string;
  average: string;
  qualified: string;
  notQualified: string;
  place: string;
  semiClosed: string;
  semiComingSoon: string;
  currentScore: string;
  rateCountry: string;
  flagAlt: string;
  finalist: string;
  saveOnlineError: string;
  saveNameFirst: string;
  shareTitle: string;
  shareText: string;
  shareReady: string;
  linkCopied: string;
  promptCopy: string;
  nameSaved: string;
  exported: string;
  imported: string;
  importError: string;
  resetConfirm: string;
  resetDone: string;
  viewCountry: string;
};

type HistoryLabels = {
  eyebrow: string;
  title: string;
  copy: string;
  voteCta: string;
  statsCta: string;
  homeCta: string;
  unavailableTitle: string;
  unavailableCopy: string;
  summaryLabel: string;
  editions: string;
  period: string;
  participations: string;
  countries: string;
  filtersLabel: string;
  search: string;
  searchPlaceholder: string;
  from: string;
  firstYear: string;
  to: string;
  lastYear: string;
  order: string;
  newest: string;
  oldest: string;
  loaded: string;
  winnersEyebrow: string;
  latestFestivals: string;
  noWinner: string;
  pendingResult: string;
  noDetailedResults: string;
  country: string;
  artist: string;
  song: string;
  points: string;
  showingParticipants: string;
  edition: string;
  winner: string;
  venue: string;
  participants: string;
  date: string;
  unknownWinner: string;
  pendingSong: string;
  viewParticipants: string;
  found: string;
  noResultsTitle: string;
  noResultsCopy: string;
};

export const voteLabels: Record<Locale, VoteLabels> = {
  es: {
    eyebrow: 'Votación Eurovision 2026', heading: 'Vota tus canciones favoritas de Eurovision 2026', copy: 'Puntúa cada país del 0 al 10 en las semifinales y en la final. Guarda tus votos, compártelos y compara tus resultados con otros eurofans.', profile: 'Tu perfil', guest: 'Votante invitado', changeName: 'Cambiar nombre', shareVotes: 'Compartir mis votos', tabsLabel: 'Semifinales y final de Eurovision 2026', selectedShow: 'Gala seleccionada', votedSongs: 'Canciones votadas', saveStatus: 'Estado de guardado', localSaved: 'Guardado local', onlineSaved: 'Guardado online', saving: 'Guardando...', missingName: 'Falta nombre', closed: 'Votación cerrada', comingSoon: 'Próximamente', pending: 'Pendiente', nameTitle: 'Elige un nombre para tus votos', nameCopy: 'Así podrás identificar tus puntuaciones y compartirlas con otros seguidores de Eurovision.', nameLabel: 'Nombre', saveName: 'Guardar nombre', votesEyebrow: 'Tus votaciones', votesTitle: 'Guardar, importar o reiniciar votos', closeSettings: 'Cerrar ajustes', exportVotes: 'Exportar votos', importVotes: 'Importar votos', deleteVotes: 'Borrar votos', noSongs: 'Las canciones de esta gala se mostrarán cuando estén disponibles.', average: 'Media', qualified: 'Clasificado para la final', notQualified: 'No clasificado', place: 'Puesto', semiClosed: 'La votación de esta semifinal ya está cerrada.', semiComingSoon: 'La votación de esta semifinal se abrirá próximamente.', currentScore: 'Puntuación actual', rateCountry: 'Puntuar {country} del 0 al 10', flagAlt: 'Bandera de {country}', finalist: 'Finalista directo', saveOnlineError: 'No se pudieron guardar los votos online. Se mantienen guardados en este dispositivo.', saveNameFirst: 'Guarda tu nombre antes de compartir tus votaciones.', shareTitle: 'Votaciones de {name} en Eurovision 2026', shareText: 'Consulta mis votaciones de Eurovision 2026.', shareReady: 'Enlace preparado para compartir.', linkCopied: 'Enlace copiado al portapapeles.', promptCopy: 'Copia este enlace para compartir tus votaciones:', nameSaved: 'Nombre guardado.', exported: 'Archivo de votos exportado correctamente.', imported: 'Votos importados correctamente.', importError: 'No se pudo importar el archivo de votos. Revisa el formato e inténtalo de nuevo.', resetConfirm: '¿Seguro que quieres borrar todos los votos guardados?', resetDone: 'Votos borrados correctamente.', viewCountry: 'Ver ficha de {country}'
  },
  en: {
    eyebrow: 'Eurovision 2026 voting', heading: 'Vote for your favourite Eurovision 2026 songs', copy: 'Rate every country from 0 to 10 in the semi-finals and the final. Save your votes, share them and compare your results with other Eurovision fans.', profile: 'Your profile', guest: 'Guest voter', changeName: 'Change name', shareVotes: 'Share my votes', tabsLabel: 'Eurovision 2026 semi-finals and final', selectedShow: 'Selected show', votedSongs: 'Songs voted', saveStatus: 'Save status', localSaved: 'Saved locally', onlineSaved: 'Saved online', saving: 'Saving...', missingName: 'Name needed', closed: 'Voting closed', comingSoon: 'Coming soon', pending: 'Pending', nameTitle: 'Choose a name for your votes', nameCopy: 'This helps identify your scores and share them with other Eurovision fans.', nameLabel: 'Name', saveName: 'Save name', votesEyebrow: 'Your votes', votesTitle: 'Save, import or reset votes', closeSettings: 'Close settings', exportVotes: 'Export votes', importVotes: 'Import votes', deleteVotes: 'Delete votes', noSongs: 'The songs for this show will appear when they are available.', average: 'Average', qualified: 'Qualified for the final', notQualified: 'Not qualified', place: 'Place', semiClosed: 'Voting for this semi-final is already closed.', semiComingSoon: 'Voting for this semi-final will open soon.', currentScore: 'Current score', rateCountry: 'Rate {country} from 0 to 10', flagAlt: 'Flag of {country}', finalist: 'Direct finalist', saveOnlineError: 'Votes could not be saved online. They remain saved on this device.', saveNameFirst: 'Save your name before sharing your votes.', shareTitle: '{name}’s Eurovision 2026 votes', shareText: 'Check out my Eurovision 2026 votes.', shareReady: 'Link ready to share.', linkCopied: 'Link copied to clipboard.', promptCopy: 'Copy this link to share your votes:', nameSaved: 'Name saved.', exported: 'Vote file exported successfully.', imported: 'Votes imported successfully.', importError: 'The vote file could not be imported. Check the format and try again.', resetConfirm: 'Are you sure you want to delete all saved votes?', resetDone: 'Votes deleted successfully.', viewCountry: 'View {country} profile'
  },
  fr: {
    eyebrow: 'Vote Eurovision 2026', heading: 'Votez pour vos chansons préférées de l’Eurovision 2026', copy: 'Notez chaque pays de 0 à 10 en demi-finales et en finale. Enregistrez vos votes, partagez-les et comparez vos résultats avec d’autres fans.', profile: 'Votre profil', guest: 'Votant invité', changeName: 'Changer de nom', shareVotes: 'Partager mes votes', tabsLabel: 'Demi-finales et finale de l’Eurovision 2026', selectedShow: 'Gala sélectionné', votedSongs: 'Chansons votées', saveStatus: 'État de sauvegarde', localSaved: 'Sauvegarde locale', onlineSaved: 'Sauvegardé en ligne', saving: 'Sauvegarde...', missingName: 'Nom requis', closed: 'Vote fermé', comingSoon: 'Bientôt', pending: 'En attente', nameTitle: 'Choisissez un nom pour vos votes', nameCopy: 'Il servira à identifier vos notes et à les partager avec d’autres fans de l’Eurovision.', nameLabel: 'Nom', saveName: 'Enregistrer le nom', votesEyebrow: 'Vos votes', votesTitle: 'Enregistrer, importer ou réinitialiser les votes', closeSettings: 'Fermer les réglages', exportVotes: 'Exporter les votes', importVotes: 'Importer les votes', deleteVotes: 'Supprimer les votes', noSongs: 'Les chansons de ce gala seront affichées dès qu’elles seront disponibles.', average: 'Moyenne', qualified: 'Qualifié pour la finale', notQualified: 'Non qualifié', place: 'Place', semiClosed: 'Le vote de cette demi-finale est déjà fermé.', semiComingSoon: 'Le vote de cette demi-finale ouvrira bientôt.', currentScore: 'Note actuelle', rateCountry: 'Noter {country} de 0 à 10', flagAlt: 'Drapeau de {country}', finalist: 'Finaliste direct', saveOnlineError: 'Les votes n’ont pas pu être sauvegardés en ligne. Ils restent enregistrés sur cet appareil.', saveNameFirst: 'Enregistrez votre nom avant de partager vos votes.', shareTitle: 'Votes de {name} pour l’Eurovision 2026', shareText: 'Consultez mes votes pour l’Eurovision 2026.', shareReady: 'Lien prêt à partager.', linkCopied: 'Lien copié dans le presse-papiers.', promptCopy: 'Copiez ce lien pour partager vos votes :', nameSaved: 'Nom enregistré.', exported: 'Fichier de votes exporté correctement.', imported: 'Votes importés correctement.', importError: 'Impossible d’importer le fichier de votes. Vérifiez le format et réessayez.', resetConfirm: 'Voulez-vous vraiment supprimer tous les votes enregistrés ?', resetDone: 'Votes supprimés correctement.', viewCountry: 'Voir la fiche de {country}'
  },
  pt: {
    eyebrow: 'Votação Eurovisão 2026', heading: 'Vote nas suas canções favoritas da Eurovisão 2026', copy: 'Pontue cada país de 0 a 10 nas semifinais e na final. Guarde os seus votos, partilhe-os e compare resultados com outros fãs.', profile: 'O seu perfil', guest: 'Votante convidado', changeName: 'Alterar nome', shareVotes: 'Partilhar os meus votos', tabsLabel: 'Semifinais e final da Eurovisão 2026', selectedShow: 'Gala selecionada', votedSongs: 'Canções votadas', saveStatus: 'Estado de gravação', localSaved: 'Guardado localmente', onlineSaved: 'Guardado online', saving: 'A guardar...', missingName: 'Falta nome', closed: 'Votação fechada', comingSoon: 'Em breve', pending: 'Pendente', nameTitle: 'Escolha um nome para os seus votos', nameCopy: 'Assim poderá identificar as suas pontuações e partilhá-las com outros fãs da Eurovisão.', nameLabel: 'Nome', saveName: 'Guardar nome', votesEyebrow: 'As suas votações', votesTitle: 'Guardar, importar ou reiniciar votos', closeSettings: 'Fechar definições', exportVotes: 'Exportar votos', importVotes: 'Importar votos', deleteVotes: 'Apagar votos', noSongs: 'As canções desta gala serão mostradas quando estiverem disponíveis.', average: 'Média', qualified: 'Classificado para a final', notQualified: 'Não classificado', place: 'Lugar', semiClosed: 'A votação desta semifinal já está fechada.', semiComingSoon: 'A votação desta semifinal abrirá em breve.', currentScore: 'Pontuação atual', rateCountry: 'Pontuar {country} de 0 a 10', flagAlt: 'Bandeira de {country}', finalist: 'Finalista direto', saveOnlineError: 'Não foi possível guardar os votos online. Continuam guardados neste dispositivo.', saveNameFirst: 'Guarde o seu nome antes de partilhar as votações.', shareTitle: 'Votações de {name} na Eurovisão 2026', shareText: 'Veja as minhas votações da Eurovisão 2026.', shareReady: 'Ligação pronta para partilhar.', linkCopied: 'Ligação copiada para a área de transferência.', promptCopy: 'Copie esta ligação para partilhar as suas votações:', nameSaved: 'Nome guardado.', exported: 'Ficheiro de votos exportado corretamente.', imported: 'Votos importados corretamente.', importError: 'Não foi possível importar o ficheiro de votos. Verifique o formato e tente novamente.', resetConfirm: 'Tem a certeza de que quer apagar todos os votos guardados?', resetDone: 'Votos apagados corretamente.', viewCountry: 'Ver ficha de {country}'
  },
  ca: {
    eyebrow: 'Votació Eurovisió 2026', heading: 'Vota les teves cançons preferides d’Eurovisió 2026', copy: 'Puntua cada país del 0 al 10 a les semifinals i a la final. Desa els teus vots, comparteix-los i compara resultats amb altres fans.', profile: 'El teu perfil', guest: 'Votant convidat', changeName: 'Canviar nom', shareVotes: 'Compartir els meus vots', tabsLabel: 'Semifinals i final d’Eurovisió 2026', selectedShow: 'Gala seleccionada', votedSongs: 'Cançons votades', saveStatus: 'Estat del desament', localSaved: 'Desat localment', onlineSaved: 'Desat en línia', saving: 'Desant...', missingName: 'Falta el nom', closed: 'Votació tancada', comingSoon: 'Properament', pending: 'Pendent', nameTitle: 'Tria un nom per als teus vots', nameCopy: 'Així podràs identificar les puntuacions i compartir-les amb altres seguidors d’Eurovisió.', nameLabel: 'Nom', saveName: 'Desar nom', votesEyebrow: 'Les teves votacions', votesTitle: 'Desar, importar o reiniciar vots', closeSettings: 'Tancar ajustos', exportVotes: 'Exportar vots', importVotes: 'Importar vots', deleteVotes: 'Esborrar vots', noSongs: 'Les cançons d’aquesta gala es mostraran quan estiguin disponibles.', average: 'Mitjana', qualified: 'Classificat per a la final', notQualified: 'No classificat', place: 'Posició', semiClosed: 'La votació d’aquesta semifinal ja està tancada.', semiComingSoon: 'La votació d’aquesta semifinal s’obrirà properament.', currentScore: 'Puntuació actual', rateCountry: 'Puntuar {country} del 0 al 10', flagAlt: 'Bandera de {country}', finalist: 'Finalista directe', saveOnlineError: 'No s’han pogut desar els vots en línia. Es mantenen desats en aquest dispositiu.', saveNameFirst: 'Desa el teu nom abans de compartir les votacions.', shareTitle: 'Votacions de {name} a Eurovisió 2026', shareText: 'Consulta les meves votacions d’Eurovisió 2026.', shareReady: 'Enllaç preparat per compartir.', linkCopied: 'Enllaç copiat al porta-retalls.', promptCopy: 'Copia aquest enllaç per compartir les teves votacions:', nameSaved: 'Nom desat.', exported: 'Fitxer de vots exportat correctament.', imported: 'Vots importats correctament.', importError: 'No s’ha pogut importar el fitxer de vots. Revisa el format i torna-ho a provar.', resetConfirm: 'Segur que vols esborrar tots els vots desats?', resetDone: 'Vots esborrats correctament.', viewCountry: 'Veure fitxa de {country}'
  },
  eu: {
    eyebrow: 'Eurovision 2026 bozketa', heading: 'Bozkatu Eurovision 2026ko zure abesti gogokoenak', copy: 'Eman 0tik 10era puntuazioa herrialde bakoitzari finalerdietan eta finalean. Gorde botoak, partekatu eta alderatu beste zaleekin.', profile: 'Zure profila', guest: 'Gonbidatutako bozkatzailea', changeName: 'Izena aldatu', shareVotes: 'Nire botoak partekatu', tabsLabel: 'Eurovision 2026ko finalerdiak eta finala', selectedShow: 'Aukeratutako gala', votedSongs: 'Bozkatutako abestiak', saveStatus: 'Gordetze egoera', localSaved: 'Lokalean gordeta', onlineSaved: 'Online gordeta', saving: 'Gordetzen...', missingName: 'Izena falta da', closed: 'Bozketa itxita', comingSoon: 'Laster', pending: 'Zain', nameTitle: 'Aukeratu izen bat zure botoetarako', nameCopy: 'Horrela zure puntuazioak identifikatu eta beste Eurovision zaleekin partekatu ahal izango dituzu.', nameLabel: 'Izena', saveName: 'Izena gorde', votesEyebrow: 'Zure botoak', votesTitle: 'Botoak gorde, inportatu edo berrabiarazi', closeSettings: 'Ezarpenak itxi', exportVotes: 'Botoak esportatu', importVotes: 'Botoak inportatu', deleteVotes: 'Botoak ezabatu', noSongs: 'Gala honetako abestiak eskuragarri daudenean agertuko dira.', average: 'Batez bestekoa', qualified: 'Finalerako sailkatua', notQualified: 'Ez sailkatua', place: 'Postua', semiClosed: 'Finalerdi honetako bozketa itxita dago.', semiComingSoon: 'Finalerdi honetako bozketa laster irekiko da.', currentScore: 'Uneko puntuazioa', rateCountry: 'Puntuatu {country} 0tik 10era', flagAlt: '{country} herrialdearen bandera', finalist: 'Finalista zuzena', saveOnlineError: 'Ezin izan dira botoak online gorde. Gailu honetan gordeta mantentzen dira.', saveNameFirst: 'Gorde izena botoak partekatu aurretik.', shareTitle: '{name}(r)en Eurovision 2026ko botoak', shareText: 'Ikusi nire Eurovision 2026ko botoak.', shareReady: 'Esteka partekatzeko prest.', linkCopied: 'Esteka arbelean kopiatu da.', promptCopy: 'Kopiatu esteka hau botoak partekatzeko:', nameSaved: 'Izena gordeta.', exported: 'Botoen fitxategia ondo esportatu da.', imported: 'Botoak ondo inportatu dira.', importError: 'Ezin izan da botoen fitxategia inportatu. Egiaztatu formatua eta saiatu berriro.', resetConfirm: 'Ziur gordetako boto guztiak ezabatu nahi dituzula?', resetDone: 'Botoak ondo ezabatu dira.', viewCountry: 'Ikusi {country} fitxa'
  },
  gl: {
    eyebrow: 'Votación Eurovisión 2026', heading: 'Vota polas túas cancións favoritas de Eurovisión 2026', copy: 'Puntúa cada país do 0 ao 10 nas semifinais e na final. Garda os teus votos, compárteos e compara resultados con outros fans.', profile: 'O teu perfil', guest: 'Votante convidado', changeName: 'Cambiar nome', shareVotes: 'Compartir os meus votos', tabsLabel: 'Semifinais e final de Eurovisión 2026', selectedShow: 'Gala seleccionada', votedSongs: 'Cancións votadas', saveStatus: 'Estado de gardado', localSaved: 'Gardado local', onlineSaved: 'Gardado online', saving: 'Gardando...', missingName: 'Falta nome', closed: 'Votación pechada', comingSoon: 'Proximamente', pending: 'Pendente', nameTitle: 'Escolle un nome para os teus votos', nameCopy: 'Así poderás identificar as túas puntuacións e compartilas con outros seguidores de Eurovisión.', nameLabel: 'Nome', saveName: 'Gardar nome', votesEyebrow: 'As túas votacións', votesTitle: 'Gardar, importar ou reiniciar votos', closeSettings: 'Pechar axustes', exportVotes: 'Exportar votos', importVotes: 'Importar votos', deleteVotes: 'Borrar votos', noSongs: 'As cancións desta gala mostraranse cando estean dispoñibles.', average: 'Media', qualified: 'Clasificado para a final', notQualified: 'Non clasificado', place: 'Posto', semiClosed: 'A votación desta semifinal xa está pechada.', semiComingSoon: 'A votación desta semifinal abrirase proximamente.', currentScore: 'Puntuación actual', rateCountry: 'Puntuar {country} do 0 ao 10', flagAlt: 'Bandeira de {country}', finalist: 'Finalista directo', saveOnlineError: 'Non se puideron gardar os votos online. Mantéñense gardados neste dispositivo.', saveNameFirst: 'Garda o teu nome antes de compartir as túas votacións.', shareTitle: 'Votacións de {name} en Eurovisión 2026', shareText: 'Consulta as miñas votacións de Eurovisión 2026.', shareReady: 'Ligazón preparada para compartir.', linkCopied: 'Ligazón copiada no portapapeis.', promptCopy: 'Copia esta ligazón para compartir as túas votacións:', nameSaved: 'Nome gardado.', exported: 'Arquivo de votos exportado correctamente.', imported: 'Votos importados correctamente.', importError: 'Non se puido importar o arquivo de votos. Revisa o formato e téntao de novo.', resetConfirm: 'Seguro que queres borrar todos os votos gardados?', resetDone: 'Votos borrados correctamente.', viewCountry: 'Ver ficha de {country}'
  },
};

export const historyLabels: Record<Locale, HistoryLabels> = {
  es: { eyebrow: 'Resultados, ganadores y países', title: 'Histórico de Eurovision', copy: 'Consulta todas las ediciones de Eurovision con sus ganadores, sedes, canciones, artistas, países participantes, posiciones y puntos. Un recorrido completo por la historia del festival año a año.', voteCta: 'Votar Eurovision 2026', statsCta: 'Ver estadísticas', homeCta: 'Ir al inicio', unavailableTitle: 'Histórico no disponible', unavailableCopy: 'Ahora mismo no se pueden mostrar los resultados históricos de Eurovision. Vuelve a intentarlo más tarde.', summaryLabel: 'Resumen del histórico de Eurovision', editions: 'Ediciones', period: 'Periodo', participations: 'Participaciones', countries: 'Países', filtersLabel: 'Filtros del histórico de Eurovision', search: 'Buscar', searchPlaceholder: 'País, artista, canción, ciudad...', from: 'Desde', firstYear: 'Primer año', to: 'Hasta', lastYear: 'Último año', order: 'Orden', newest: 'Más recientes primero', oldest: 'Más antiguos primero', loaded: 'ediciones cargadas.', winnersEyebrow: 'Ganadores de Eurovision', latestFestivals: 'Últimos festivales', noWinner: 'Sin ganador', pendingResult: 'Resultado pendiente', noDetailedResults: 'No hay resultados detallados para esta edición de Eurovision.', country: 'País', artist: 'Artista', song: 'Canción', points: 'Puntos', showingParticipants: 'Mostrando {shown} de {total} países participantes.', edition: 'Edición', winner: 'Ganador', venue: 'Recinto', participants: 'Participantes', date: 'Fecha', unknownWinner: 'Ganador no disponible', pendingSong: 'Canción y artista pendientes de confirmar.', viewParticipants: 'Ver resultados y participantes', found: 'ediciones de Eurovision encontradas.', noResultsTitle: 'No hay resultados', noResultsCopy: 'Prueba con otro país, artista, canción, ciudad o rango de años.' },
  en: { eyebrow: 'Results, winners and countries', title: 'Eurovision history', copy: 'Explore every Eurovision edition with winners, host cities, songs, artists, participating countries, rankings and points. A year-by-year guide to the festival history.', voteCta: 'Vote Eurovision 2026', statsCta: 'View statistics', homeCta: 'Go home', unavailableTitle: 'History unavailable', unavailableCopy: 'Historical Eurovision results cannot be shown right now. Please try again later.', summaryLabel: 'Eurovision history summary', editions: 'Editions', period: 'Period', participations: 'Participations', countries: 'Countries', filtersLabel: 'Eurovision history filters', search: 'Search', searchPlaceholder: 'Country, artist, song, city...', from: 'From', firstYear: 'First year', to: 'To', lastYear: 'Last year', order: 'Order', newest: 'Newest first', oldest: 'Oldest first', loaded: 'editions loaded.', winnersEyebrow: 'Eurovision winners', latestFestivals: 'Latest festivals', noWinner: 'No winner', pendingResult: 'Result pending', noDetailedResults: 'No detailed results are available for this Eurovision edition.', country: 'Country', artist: 'Artist', song: 'Song', points: 'Points', showingParticipants: 'Showing {shown} of {total} participating countries.', edition: 'Edition', winner: 'Winner', venue: 'Venue', participants: 'Participants', date: 'Date', unknownWinner: 'Winner unavailable', pendingSong: 'Song and artist pending confirmation.', viewParticipants: 'View results and participants', found: 'Eurovision editions found.', noResultsTitle: 'No results', noResultsCopy: 'Try another country, artist, song, city or year range.' },
  fr: { eyebrow: 'Résultats, gagnants et pays', title: 'Historique de l’Eurovision', copy: 'Consultez toutes les éditions de l’Eurovision avec gagnants, villes hôtes, chansons, artistes, pays participants, classements et points.', voteCta: 'Voter Eurovision 2026', statsCta: 'Voir les statistiques', homeCta: 'Accueil', unavailableTitle: 'Historique indisponible', unavailableCopy: 'Les résultats historiques de l’Eurovision ne peuvent pas être affichés pour le moment. Réessayez plus tard.', summaryLabel: 'Résumé de l’historique de l’Eurovision', editions: 'Éditions', period: 'Période', participations: 'Participations', countries: 'Pays', filtersLabel: 'Filtres de l’historique Eurovision', search: 'Rechercher', searchPlaceholder: 'Pays, artiste, chanson, ville...', from: 'Depuis', firstYear: 'Première année', to: 'Jusqu’à', lastYear: 'Dernière année', order: 'Ordre', newest: 'Plus récents d’abord', oldest: 'Plus anciens d’abord', loaded: 'éditions chargées.', winnersEyebrow: 'Gagnants de l’Eurovision', latestFestivals: 'Derniers festivals', noWinner: 'Aucun gagnant', pendingResult: 'Résultat en attente', noDetailedResults: 'Aucun résultat détaillé disponible pour cette édition de l’Eurovision.', country: 'Pays', artist: 'Artiste', song: 'Chanson', points: 'Points', showingParticipants: '{shown} pays participants affichés sur {total}.', edition: 'Édition', winner: 'Gagnant', venue: 'Salle', participants: 'Participants', date: 'Date', unknownWinner: 'Gagnant indisponible', pendingSong: 'Chanson et artiste en attente de confirmation.', viewParticipants: 'Voir résultats et participants', found: 'éditions de l’Eurovision trouvées.', noResultsTitle: 'Aucun résultat', noResultsCopy: 'Essayez un autre pays, artiste, chanson, ville ou intervalle d’années.' },
  pt: { eyebrow: 'Resultados, vencedores e países', title: 'Histórico da Eurovisão', copy: 'Consulte todas as edições da Eurovisão com vencedores, cidades anfitriãs, canções, artistas, países participantes, posições e pontos.', voteCta: 'Votar na Eurovisão 2026', statsCta: 'Ver estatísticas', homeCta: 'Ir para o início', unavailableTitle: 'Histórico indisponível', unavailableCopy: 'Neste momento não é possível mostrar os resultados históricos da Eurovisão. Tente novamente mais tarde.', summaryLabel: 'Resumo do histórico da Eurovisão', editions: 'Edições', period: 'Período', participations: 'Participações', countries: 'Países', filtersLabel: 'Filtros do histórico da Eurovisão', search: 'Procurar', searchPlaceholder: 'País, artista, canção, cidade...', from: 'Desde', firstYear: 'Primeiro ano', to: 'Até', lastYear: 'Último ano', order: 'Ordem', newest: 'Mais recentes primeiro', oldest: 'Mais antigos primeiro', loaded: 'edições carregadas.', winnersEyebrow: 'Vencedores da Eurovisão', latestFestivals: 'Últimos festivais', noWinner: 'Sem vencedor', pendingResult: 'Resultado pendente', noDetailedResults: 'Não há resultados detalhados para esta edição da Eurovisão.', country: 'País', artist: 'Artista', song: 'Canção', points: 'Pontos', showingParticipants: 'A mostrar {shown} de {total} países participantes.', edition: 'Edição', winner: 'Vencedor', venue: 'Recinto', participants: 'Participantes', date: 'Data', unknownWinner: 'Vencedor indisponível', pendingSong: 'Canção e artista pendentes de confirmação.', viewParticipants: 'Ver resultados e participantes', found: 'edições da Eurovisão encontradas.', noResultsTitle: 'Sem resultados', noResultsCopy: 'Experimente outro país, artista, canção, cidade ou intervalo de anos.' },
  ca: { eyebrow: 'Resultats, guanyadors i països', title: 'Històric d’Eurovisió', copy: 'Consulta totes les edicions d’Eurovisió amb guanyadors, seus, cançons, artistes, països participants, posicions i punts.', voteCta: 'Vota Eurovisió 2026', statsCta: 'Veure estadístiques', homeCta: 'Anar a l’inici', unavailableTitle: 'Històric no disponible', unavailableCopy: 'Ara mateix no es poden mostrar els resultats històrics d’Eurovisió. Torna-ho a provar més tard.', summaryLabel: 'Resum de l’històric d’Eurovisió', editions: 'Edicions', period: 'Període', participations: 'Participacions', countries: 'Països', filtersLabel: 'Filtres de l’històric d’Eurovisió', search: 'Buscar', searchPlaceholder: 'País, artista, cançó, ciutat...', from: 'Des de', firstYear: 'Primer any', to: 'Fins a', lastYear: 'Últim any', order: 'Ordre', newest: 'Més recents primer', oldest: 'Més antics primer', loaded: 'edicions carregades.', winnersEyebrow: 'Guanyadors d’Eurovisió', latestFestivals: 'Últims festivals', noWinner: 'Sense guanyador', pendingResult: 'Resultat pendent', noDetailedResults: 'No hi ha resultats detallats per a aquesta edició d’Eurovisió.', country: 'País', artist: 'Artista', song: 'Cançó', points: 'Punts', showingParticipants: 'Mostrant {shown} de {total} països participants.', edition: 'Edició', winner: 'Guanyador', venue: 'Recinte', participants: 'Participants', date: 'Data', unknownWinner: 'Guanyador no disponible', pendingSong: 'Cançó i artista pendents de confirmar.', viewParticipants: 'Veure resultats i participants', found: 'edicions d’Eurovisió trobades.', noResultsTitle: 'No hi ha resultats', noResultsCopy: 'Prova amb un altre país, artista, cançó, ciutat o rang d’anys.' },
  eu: { eyebrow: 'Emaitzak, irabazleak eta herrialdeak', title: 'Eurovisioneko historikoa', copy: 'Kontsultatu Eurovisioneko edizio guztiak: irabazleak, egoitzak, abestiak, artistak, parte-hartzaileak, postuak eta puntuak.', voteCta: 'Bozkatu Eurovision 2026', statsCta: 'Ikusi estatistikak', homeCta: 'Joan hasierara', unavailableTitle: 'Historikoa ez dago erabilgarri', unavailableCopy: 'Une honetan ezin dira Eurovisioneko emaitza historikoak erakutsi. Saiatu berriro geroago.', summaryLabel: 'Eurovisioneko historikoaren laburpena', editions: 'Edizioak', period: 'Aldia', participations: 'Parte-hartzeak', countries: 'Herrialdeak', filtersLabel: 'Eurovisioneko historikoaren iragazkiak', search: 'Bilatu', searchPlaceholder: 'Herrialdea, artista, abestia, hiria...', from: 'Noiztik', firstYear: 'Lehen urtea', to: 'Noiz arte', lastYear: 'Azken urtea', order: 'Ordena', newest: 'Berrienak lehenik', oldest: 'Zaharrenak lehenik', loaded: 'edizio kargatuta.', winnersEyebrow: 'Eurovisioneko irabazleak', latestFestivals: 'Azken jaialdiak', noWinner: 'Irabazlerik gabe', pendingResult: 'Emaitza zain', noDetailedResults: 'Ez dago emaitza zehatzik Eurovisioneko edizio honetarako.', country: 'Herrialdea', artist: 'Artista', song: 'Abestia', points: 'Puntuak', showingParticipants: '{shown}/{total} herrialde parte-hartzaile erakusten.', edition: 'Edizioa', winner: 'Irabazlea', venue: 'Aretoa', participants: 'Parte-hartzaileak', date: 'Data', unknownWinner: 'Irabazlea ez dago erabilgarri', pendingSong: 'Abestia eta artista baieztatu gabe.', viewParticipants: 'Ikusi emaitzak eta parte-hartzaileak', found: 'Eurovisioneko edizio aurkituta.', noResultsTitle: 'Ez dago emaitzarik', noResultsCopy: 'Saiatu beste herrialde, artista, abesti, hiri edo urte tarte batekin.' },
  gl: { eyebrow: 'Resultados, gañadores e países', title: 'Histórico de Eurovisión', copy: 'Consulta todas as edicións de Eurovisión cos seus gañadores, sedes, cancións, artistas, países participantes, posicións e puntos.', voteCta: 'Votar Eurovisión 2026', statsCta: 'Ver estatísticas', homeCta: 'Ir ao inicio', unavailableTitle: 'Histórico non dispoñible', unavailableCopy: 'Agora mesmo non se poden mostrar os resultados históricos de Eurovisión. Téntao de novo máis tarde.', summaryLabel: 'Resumo do histórico de Eurovisión', editions: 'Edicións', period: 'Período', participations: 'Participacións', countries: 'Países', filtersLabel: 'Filtros do histórico de Eurovisión', search: 'Buscar', searchPlaceholder: 'País, artista, canción, cidade...', from: 'Desde', firstYear: 'Primeiro ano', to: 'Ata', lastYear: 'Último ano', order: 'Orde', newest: 'Máis recentes primeiro', oldest: 'Máis antigos primeiro', loaded: 'edicións cargadas.', winnersEyebrow: 'Gañadores de Eurovisión', latestFestivals: 'Últimos festivais', noWinner: 'Sen gañador', pendingResult: 'Resultado pendente', noDetailedResults: 'Non hai resultados detallados para esta edición de Eurovisión.', country: 'País', artist: 'Artista', song: 'Canción', points: 'Puntos', showingParticipants: 'Mostrando {shown} de {total} países participantes.', edition: 'Edición', winner: 'Gañador', venue: 'Recinto', participants: 'Participantes', date: 'Data', unknownWinner: 'Gañador non dispoñible', pendingSong: 'Canción e artista pendentes de confirmar.', viewParticipants: 'Ver resultados e participantes', found: 'edicións de Eurovisión atopadas.', noResultsTitle: 'Non hai resultados', noResultsCopy: 'Proba con outro país, artista, canción, cidade ou rango de anos.' },
};

export function getVoteLabels(locale: Locale) {
  return voteLabels[locale] ?? voteLabels[defaultLocale];
}

export function getHistoryLabels(locale: Locale) {
  return historyLabels[locale] ?? historyLabels[defaultLocale];
}
