import { type Locale } from '../config/site';

type PredictionLabels = {
  title: string;
  description: string;
  eyebrow: string;
  heading: string;
  copy: string;
  nameLabel: string;
  namePlaceholder: string;
  winnerTitle: string;
  winnerLabel: string;
  topTitle: string;
  topCopy: string;
  positionLabel: string;
  emptyOption: string;
  pickTitle: string;
  pickCopy: string;
  selectedSlot: string;
  saveStatus: string;
  saved: string;
  shareTitle: string;
  shareCopy: string;
  copySummary: string;
  copyLink: string;
  previewImage: string;
  previewTitle: string;
  closePreview: string;
  shareImage: string;
  downloadImage: string;
  reset: string;
  missingPrediction: string;
  readyTitle: string;
  readyCopy: string;
  summaryTitle: string;
  byName: string;
  winnerSummary: string;
  topSummary: string;
  copied: string;
  linkCopied: string;
  imageDownloaded: string;
  imageShared: string;
  imageError: string;
  shareUnavailable: string;
  resetDone: string;
  resetConfirm: string;
  flagAlt: string;
  viewCountry: string;
  credit: string;
};

const predictionLabels: Record<Locale, PredictionLabels> = {
  es: { title: 'Quiniela Eurovision 2026', description: 'Crea y comparte tu predicción para Eurovision 2026 con ganador y top 10 guardados en este dispositivo.', eyebrow: 'Quiniela Eurovision 2026', heading: 'Predice ganador y top 10', copy: 'Elige tu ganador y construye un top visual. Con un solo país ya puedes compartir tu quiniela.', nameLabel: 'Tu nombre', namePlaceholder: 'Ej. Jorge', winnerTitle: 'Ganador previsto', winnerLabel: 'País ganador', topTitle: 'Top previsto', topCopy: 'Toca un puesto y después elige un país. Puedes completar solo los puestos que quieras.', positionLabel: 'Puesto {position}', emptyOption: 'Selecciona un país', pickTitle: 'Elige países para el top', pickCopy: 'Selecciona primero un puesto del top y luego toca una tarjeta de país.', selectedSlot: 'Puesto activo: {position}', saveStatus: 'Estado', saved: 'Guardado en este dispositivo', shareTitle: 'Compartir quiniela', shareCopy: 'Comparte una página con tu nombre y tu predicción, copia un resumen o descarga una imagen.', copySummary: 'Copiar resumen', copyLink: 'Copiar enlace', previewImage: 'Previsualizar imagen', previewTitle: 'Previsualización de la quiniela', closePreview: 'Cerrar', shareImage: 'Compartir imagen', downloadImage: 'Descargar imagen', reset: 'Reiniciar quiniela', missingPrediction: 'Añade al menos un país o un ganador para compartir.', readyTitle: 'Quiniela lista', readyCopy: 'Tu predicción está guardada y preparada para compartir.', summaryTitle: 'Mi quiniela de Eurovision 2026', byName: 'Quiniela de {name}', winnerSummary: 'Ganador: {country}', topSummary: 'Top:', copied: 'Resumen copiado al portapapeles.', linkCopied: 'Enlace copiado al portapapeles.', imageDownloaded: 'Imagen descargada correctamente.', imageShared: 'Imagen compartida correctamente.', imageError: 'No se pudo generar la imagen en este navegador.', shareUnavailable: 'No se puede compartir la imagen directamente en este navegador.', resetDone: 'Quiniela reiniciada.', resetConfirm: '¿Seguro que quieres borrar tu quiniela?', flagAlt: 'Bandera de {country}', viewCountry: 'Ver ficha de {country}', credit: 'eurovision.alon.one' },
  en: { title: 'Eurovision 2026 prediction', description: 'Create and share your Eurovision 2026 prediction with winner and top saved on this device.', eyebrow: 'Eurovision 2026 prediction', heading: 'Predict the winner and top 10', copy: 'Pick your winner and build a visual top. One country is enough to share your prediction.', nameLabel: 'Your name', namePlaceholder: 'e.g. Jorge', winnerTitle: 'Predicted winner', winnerLabel: 'Winning country', topTitle: 'Predicted top', topCopy: 'Tap a place and then choose a country. Fill only the positions you want.', positionLabel: 'Place {position}', emptyOption: 'Select a country', pickTitle: 'Choose countries for the top', pickCopy: 'First select a top place, then tap a country card.', selectedSlot: 'Active place: {position}', saveStatus: 'Status', saved: 'Saved on this device', shareTitle: 'Share prediction', shareCopy: 'Share a page with your name and prediction, copy a summary or download an image.', copySummary: 'Copy summary', copyLink: 'Copy link', previewImage: 'Preview image', previewTitle: 'Prediction preview', closePreview: 'Close', shareImage: 'Share image', downloadImage: 'Download image', reset: 'Reset prediction', missingPrediction: 'Add at least one country or a winner to share.', readyTitle: 'Prediction ready', readyCopy: 'Your prediction is saved and ready to share.', summaryTitle: 'My Eurovision 2026 prediction', byName: '{name}’s prediction', winnerSummary: 'Winner: {country}', topSummary: 'Top:', copied: 'Summary copied to clipboard.', linkCopied: 'Link copied to clipboard.', imageDownloaded: 'Image downloaded successfully.', imageShared: 'Image shared successfully.', imageError: 'The image could not be generated in this browser.', shareUnavailable: 'Direct image sharing is not available in this browser.', resetDone: 'Prediction reset.', resetConfirm: 'Are you sure you want to delete your prediction?', flagAlt: 'Flag of {country}', viewCountry: 'View {country} profile', credit: 'eurovision.alon.one' },
  fr: { title: 'Pronostic Eurovision 2026', description: 'Créez et partagez votre pronostic pour l’Eurovision 2026 avec gagnant et top sauvegardés sur cet appareil.', eyebrow: 'Pronostic Eurovision 2026', heading: 'Prédisez le gagnant et le top 10', copy: 'Choisissez votre gagnant et construisez un top visuel. Un seul pays suffit pour partager votre pronostic.', nameLabel: 'Votre nom', namePlaceholder: 'Ex. Jorge', winnerTitle: 'Gagnant prévu', winnerLabel: 'Pays gagnant', topTitle: 'Top prévu', topCopy: 'Touchez une place puis choisissez un pays. Remplissez seulement les places souhaitées.', positionLabel: 'Place {position}', emptyOption: 'Sélectionner un pays', pickTitle: 'Choisir les pays du top', pickCopy: 'Sélectionnez d’abord une place, puis touchez une carte pays.', selectedSlot: 'Place active : {position}', saveStatus: 'État', saved: 'Sauvegardé sur cet appareil', shareTitle: 'Partager le pronostic', shareCopy: 'Partagez une page avec votre nom et votre pronostic, copiez un résumé ou téléchargez une image.', copySummary: 'Copier le résumé', copyLink: 'Copier le lien', previewImage: 'Prévisualiser l’image', previewTitle: 'Aperçu du pronostic', closePreview: 'Fermer', shareImage: 'Partager l’image', downloadImage: 'Télécharger l’image', reset: 'Réinitialiser', missingPrediction: 'Ajoutez au moins un pays ou un gagnant pour partager.', readyTitle: 'Pronostic prêt', readyCopy: 'Votre pronostic est sauvegardé et prêt à partager.', summaryTitle: 'Mon pronostic Eurovision 2026', byName: 'Pronostic de {name}', winnerSummary: 'Gagnant : {country}', topSummary: 'Top :', copied: 'Résumé copié dans le presse-papiers.', linkCopied: 'Lien copié dans le presse-papiers.', imageDownloaded: 'Image téléchargée correctement.', imageShared: 'Image partagée correctement.', imageError: 'Impossible de générer l’image dans ce navigateur.', shareUnavailable: 'Le partage direct de l’image n’est pas disponible dans ce navigateur.', resetDone: 'Pronostic réinitialisé.', resetConfirm: 'Voulez-vous vraiment supprimer votre pronostic ?', flagAlt: 'Drapeau de {country}', viewCountry: 'Voir la fiche de {country}', credit: 'eurovision.alon.one' },
  pt: { title: 'Prognóstico Eurovisão 2026', description: 'Crie e partilhe o seu prognóstico para a Eurovisão 2026 com vencedor e top guardados neste dispositivo.', eyebrow: 'Prognóstico Eurovisão 2026', heading: 'Preveja vencedor e top 10', copy: 'Escolha o vencedor e construa um top visual. Um só país já chega para partilhar o prognóstico.', nameLabel: 'O seu nome', namePlaceholder: 'Ex. Jorge', winnerTitle: 'Vencedor previsto', winnerLabel: 'País vencedor', topTitle: 'Top previsto', topCopy: 'Toque num lugar e depois escolha um país. Preencha apenas os lugares que quiser.', positionLabel: 'Lugar {position}', emptyOption: 'Selecionar país', pickTitle: 'Escolha países para o top', pickCopy: 'Selecione primeiro um lugar do top e depois toque num cartão de país.', selectedSlot: 'Lugar ativo: {position}', saveStatus: 'Estado', saved: 'Guardado neste dispositivo', shareTitle: 'Partilhar prognóstico', shareCopy: 'Partilhe uma página com o seu nome e prognóstico, copie um resumo ou descarregue uma imagem.', copySummary: 'Copiar resumo', copyLink: 'Copiar ligação', previewImage: 'Pré-visualizar imagem', previewTitle: 'Pré-visualização do prognóstico', closePreview: 'Fechar', shareImage: 'Partilhar imagem', downloadImage: 'Descarregar imagem', reset: 'Reiniciar prognóstico', missingPrediction: 'Adicione pelo menos um país ou um vencedor para partilhar.', readyTitle: 'Prognóstico pronto', readyCopy: 'O seu prognóstico está guardado e pronto para partilhar.', summaryTitle: 'O meu prognóstico da Eurovisão 2026', byName: 'Prognóstico de {name}', winnerSummary: 'Vencedor: {country}', topSummary: 'Top:', copied: 'Resumo copiado para a área de transferência.', linkCopied: 'Ligação copiada para a área de transferência.', imageDownloaded: 'Imagem descarregada corretamente.', imageShared: 'Imagem partilhada corretamente.', imageError: 'Não foi possível gerar a imagem neste navegador.', shareUnavailable: 'A partilha direta da imagem não está disponível neste navegador.', resetDone: 'Prognóstico reiniciado.', resetConfirm: 'Tem a certeza de que quer apagar o prognóstico?', flagAlt: 'Bandeira de {country}', viewCountry: 'Ver ficha de {country}', credit: 'eurovision.alon.one' },
  ca: { title: 'Quiniela Eurovisió 2026', description: 'Crea i comparteix la teva predicció d’Eurovisió 2026 amb guanyador i top desats en aquest dispositiu.', eyebrow: 'Quiniela Eurovisió 2026', heading: 'Prediu guanyador i top 10', copy: 'Tria el guanyador i construeix un top visual. Amb un sol país ja pots compartir la quiniela.', nameLabel: 'El teu nom', namePlaceholder: 'Ex. Jorge', winnerTitle: 'Guanyador previst', winnerLabel: 'País guanyador', topTitle: 'Top previst', topCopy: 'Toca una posició i després tria un país. Pots omplir només les posicions que vulguis.', positionLabel: 'Posició {position}', emptyOption: 'Selecciona un país', pickTitle: 'Tria països per al top', pickCopy: 'Selecciona primer una posició del top i després toca una targeta de país.', selectedSlot: 'Posició activa: {position}', saveStatus: 'Estat', saved: 'Desat en aquest dispositiu', shareTitle: 'Compartir quiniela', shareCopy: 'Comparteix una pàgina amb el teu nom i la predicció, copia un resum o descarrega una imatge.', copySummary: 'Copiar resum', copyLink: 'Copiar enllaç', previewImage: 'Previsualitzar imatge', previewTitle: 'Previsualització de la quiniela', closePreview: 'Tancar', shareImage: 'Compartir imatge', downloadImage: 'Descarregar imatge', reset: 'Reiniciar quiniela', missingPrediction: 'Afegeix almenys un país o un guanyador per compartir.', readyTitle: 'Quiniela preparada', readyCopy: 'La predicció està desada i preparada per compartir.', summaryTitle: 'La meva quiniela d’Eurovisió 2026', byName: 'Quiniela de {name}', winnerSummary: 'Guanyador: {country}', topSummary: 'Top:', copied: 'Resum copiat al porta-retalls.', linkCopied: 'Enllaç copiat al porta-retalls.', imageDownloaded: 'Imatge descarregada correctament.', imageShared: 'Imatge compartida correctament.', imageError: 'No s’ha pogut generar la imatge en aquest navegador.', shareUnavailable: 'No es pot compartir la imatge directament en aquest navegador.', resetDone: 'Quiniela reiniciada.', resetConfirm: 'Segur que vols esborrar la quiniela?', flagAlt: 'Bandera de {country}', viewCountry: 'Veure fitxa de {country}', credit: 'eurovision.alon.one' },
  eu: { title: 'Eurovision 2026 kiniela', description: 'Sortu eta partekatu Eurovision 2026rako iragarpena, irabazlea eta topa gailu honetan gordeta.', eyebrow: 'Eurovision 2026 kiniela', heading: 'Iragarri irabazlea eta top 10a', copy: 'Aukeratu irabazlea eta eraiki top bisuala. Herrialde bakarrarekin nahikoa da partekatzeko.', nameLabel: 'Zure izena', namePlaceholder: 'Adib. Jorge', winnerTitle: 'Aurreikusitako irabazlea', winnerLabel: 'Herrialde irabazlea', topTitle: 'Aurreikusitako topa', topCopy: 'Ukitu postu bat eta gero aukeratu herrialdea. Nahi dituzun postuak bakarrik bete.', positionLabel: '{position}. postua', emptyOption: 'Aukeratu herrialde bat', pickTitle: 'Aukeratu toperako herrialdeak', pickCopy: 'Lehenik aukeratu postu bat, gero ukitu herrialde-txartela.', selectedSlot: 'Postu aktiboa: {position}', saveStatus: 'Egoera', saved: 'Gailu honetan gordeta', shareTitle: 'Partekatu kiniela', shareCopy: 'Partekatu zure izena eta iragarpena dituen orria, kopiatu laburpena edo deskargatu irudia.', copySummary: 'Kopiatu laburpena', copyLink: 'Kopiatu esteka', previewImage: 'Aurreikusi irudia', previewTitle: 'Kinielaren aurrebista', closePreview: 'Itxi', shareImage: 'Partekatu irudia', downloadImage: 'Deskargatu irudia', reset: 'Berrabiarazi kiniela', missingPrediction: 'Gehitu gutxienez herrialde bat edo irabazle bat partekatzeko.', readyTitle: 'Kiniela prest', readyCopy: 'Zure iragarpena gordeta dago eta partekatzeko prest.', summaryTitle: 'Nire Eurovision 2026 kiniela', byName: '{name}(r)en kiniela', winnerSummary: 'Irabazlea: {country}', topSummary: 'Topa:', copied: 'Laburpena arbelean kopiatu da.', linkCopied: 'Esteka arbelean kopiatu da.', imageDownloaded: 'Irudia ondo deskargatu da.', imageShared: 'Irudia ondo partekatu da.', imageError: 'Ezin izan da irudia sortu nabigatzaile honetan.', shareUnavailable: 'Irudia zuzenean partekatzea ez dago erabilgarri nabigatzaile honetan.', resetDone: 'Kiniela berrabiarazi da.', resetConfirm: 'Ziur kiniela ezabatu nahi duzula?', flagAlt: '{country} herrialdearen bandera', viewCountry: 'Ikusi {country} fitxa', credit: 'eurovision.alon.one' },
  gl: { title: 'Quiniela Eurovisión 2026', description: 'Crea e comparte a túa predición para Eurovisión 2026 con gañador e top gardados neste dispositivo.', eyebrow: 'Quiniela Eurovisión 2026', heading: 'Predí gañador e top 10', copy: 'Escolle o gañador e constrúe un top visual. Cun só país xa podes compartir a quiniela.', nameLabel: 'O teu nome', namePlaceholder: 'Ex. Jorge', winnerTitle: 'Gañador previsto', winnerLabel: 'País gañador', topTitle: 'Top previsto', topCopy: 'Toca un posto e despois escolle un país. Podes cubrir só os postos que queiras.', positionLabel: 'Posto {position}', emptyOption: 'Selecciona un país', pickTitle: 'Escolle países para o top', pickCopy: 'Selecciona primeiro un posto do top e despois toca unha tarxeta de país.', selectedSlot: 'Posto activo: {position}', saveStatus: 'Estado', saved: 'Gardado neste dispositivo', shareTitle: 'Compartir quiniela', shareCopy: 'Comparte unha páxina co teu nome e a predición, copia un resumo ou descarga unha imaxe.', copySummary: 'Copiar resumo', copyLink: 'Copiar ligazón', previewImage: 'Previsualizar imaxe', previewTitle: 'Previsualización da quiniela', closePreview: 'Pechar', shareImage: 'Compartir imaxe', downloadImage: 'Descargar imaxe', reset: 'Reiniciar quiniela', missingPrediction: 'Engade polo menos un país ou un gañador para compartir.', readyTitle: 'Quiniela lista', readyCopy: 'A túa predición está gardada e preparada para compartir.', summaryTitle: 'A miña quiniela de Eurovisión 2026', byName: 'Quiniela de {name}', winnerSummary: 'Gañador: {country}', topSummary: 'Top:', copied: 'Resumo copiado no portapapeis.', linkCopied: 'Ligazón copiada no portapapeis.', imageDownloaded: 'Imaxe descargada correctamente.', imageShared: 'Imaxe compartida correctamente.', imageError: 'Non se puido xerar a imaxe neste navegador.', shareUnavailable: 'Non se pode compartir a imaxe directamente neste navegador.', resetDone: 'Quiniela reiniciada.', resetConfirm: 'Seguro que queres borrar a quiniela?', flagAlt: 'Bandeira de {country}', viewCountry: 'Ver ficha de {country}', credit: 'eurovision.alon.one' },
};

export function getPredictionLabels(locale: Locale) {
  return predictionLabels[locale] ?? predictionLabels.es;
}
