import { type Locale } from '../config/site';

type PredictionLabels = {
  title: string;
  description: string;
  eyebrow: string;
  heading: string;
  copy: string;
  winnerTitle: string;
  winnerLabel: string;
  topTitle: string;
  topCopy: string;
  positionLabel: string;
  emptyOption: string;
  saveStatus: string;
  saved: string;
  shareTitle: string;
  shareCopy: string;
  copySummary: string;
  copyLink: string;
  reset: string;
  missingWinner: string;
  missingTop: string;
  readyTitle: string;
  readyCopy: string;
  summaryTitle: string;
  winnerSummary: string;
  topSummary: string;
  copied: string;
  linkCopied: string;
  resetDone: string;
  resetConfirm: string;
  flagAlt: string;
  viewCountry: string;
};

const predictionLabels: Record<Locale, PredictionLabels> = {
  es: { title: 'Quiniela Eurovision 2026', description: 'Crea y comparte tu predicción para Eurovision 2026 con ganador y top 10 guardados en este dispositivo.', eyebrow: 'Quiniela Eurovision 2026', heading: 'Predice ganador y top 10', copy: 'Elige tu ganador y ordena tu top 10 personal. La quiniela se guarda en localStorage y puedes compartirla mediante enlace o resumen copiable.', winnerTitle: 'Ganador previsto', winnerLabel: 'País ganador', topTitle: 'Top 10 previsto', topCopy: 'Selecciona países sin repetir. Puedes completar la quiniela poco a poco.', positionLabel: 'Puesto {position}', emptyOption: 'Selecciona un país', saveStatus: 'Estado', saved: 'Guardado en este dispositivo', shareTitle: 'Compartir quiniela', shareCopy: 'Genera un enlace con tu predicción o copia un resumen accesible.', copySummary: 'Copiar resumen', copyLink: 'Copiar enlace', reset: 'Reiniciar quiniela', missingWinner: 'Elige un ganador para completar la quiniela.', missingTop: 'Añade al menos un país al top 10.', readyTitle: 'Quiniela lista', readyCopy: 'Tu predicción está guardada y preparada para compartir.', summaryTitle: 'Mi quiniela de Eurovision 2026', winnerSummary: 'Ganador: {country}', topSummary: 'Top 10:', copied: 'Resumen copiado al portapapeles.', linkCopied: 'Enlace copiado al portapapeles.', resetDone: 'Quiniela reiniciada.', resetConfirm: '¿Seguro que quieres borrar tu quiniela?', flagAlt: 'Bandera de {country}', viewCountry: 'Ver ficha de {country}' },
  en: { title: 'Eurovision 2026 prediction', description: 'Create and share your Eurovision 2026 prediction with winner and top 10 saved on this device.', eyebrow: 'Eurovision 2026 prediction', heading: 'Predict the winner and top 10', copy: 'Pick your winner and order your personal top 10. The prediction is saved in localStorage and can be shared by link or accessible summary.', winnerTitle: 'Predicted winner', winnerLabel: 'Winning country', topTitle: 'Predicted top 10', topCopy: 'Select countries without repeats. You can complete your prediction gradually.', positionLabel: 'Place {position}', emptyOption: 'Select a country', saveStatus: 'Status', saved: 'Saved on this device', shareTitle: 'Share prediction', shareCopy: 'Generate a link with your prediction or copy an accessible summary.', copySummary: 'Copy summary', copyLink: 'Copy link', reset: 'Reset prediction', missingWinner: 'Choose a winner to complete the prediction.', missingTop: 'Add at least one country to the top 10.', readyTitle: 'Prediction ready', readyCopy: 'Your prediction is saved and ready to share.', summaryTitle: 'My Eurovision 2026 prediction', winnerSummary: 'Winner: {country}', topSummary: 'Top 10:', copied: 'Summary copied to clipboard.', linkCopied: 'Link copied to clipboard.', resetDone: 'Prediction reset.', resetConfirm: 'Are you sure you want to delete your prediction?', flagAlt: 'Flag of {country}', viewCountry: 'View {country} profile' },
  fr: { title: 'Pronostic Eurovision 2026', description: 'Créez et partagez votre pronostic pour l’Eurovision 2026 avec gagnant et top 10 sauvegardés sur cet appareil.', eyebrow: 'Pronostic Eurovision 2026', heading: 'Prédisez le gagnant et le top 10', copy: 'Choisissez votre gagnant et ordonnez votre top 10 personnel. Le pronostic est sauvegardé en localStorage et partageable par lien ou résumé accessible.', winnerTitle: 'Gagnant prévu', winnerLabel: 'Pays gagnant', topTitle: 'Top 10 prévu', topCopy: 'Sélectionnez des pays sans doublon. Vous pouvez compléter le pronostic progressivement.', positionLabel: 'Place {position}', emptyOption: 'Sélectionner un pays', saveStatus: 'État', saved: 'Sauvegardé sur cet appareil', shareTitle: 'Partager le pronostic', shareCopy: 'Générez un lien avec votre pronostic ou copiez un résumé accessible.', copySummary: 'Copier le résumé', copyLink: 'Copier le lien', reset: 'Réinitialiser', missingWinner: 'Choisissez un gagnant pour compléter le pronostic.', missingTop: 'Ajoutez au moins un pays au top 10.', readyTitle: 'Pronostic prêt', readyCopy: 'Votre pronostic est sauvegardé et prêt à partager.', summaryTitle: 'Mon pronostic Eurovision 2026', winnerSummary: 'Gagnant : {country}', topSummary: 'Top 10 :', copied: 'Résumé copié dans le presse-papiers.', linkCopied: 'Lien copié dans le presse-papiers.', resetDone: 'Pronostic réinitialisé.', resetConfirm: 'Voulez-vous vraiment supprimer votre pronostic ?', flagAlt: 'Drapeau de {country}', viewCountry: 'Voir la fiche de {country}' },
  pt: { title: 'Prognóstico Eurovisão 2026', description: 'Crie e partilhe o seu prognóstico para a Eurovisão 2026 com vencedor e top 10 guardados neste dispositivo.', eyebrow: 'Prognóstico Eurovisão 2026', heading: 'Preveja vencedor e top 10', copy: 'Escolha o vencedor e ordene o seu top 10. O prognóstico fica guardado em localStorage e pode ser partilhado por ligação ou resumo acessível.', winnerTitle: 'Vencedor previsto', winnerLabel: 'País vencedor', topTitle: 'Top 10 previsto', topCopy: 'Selecione países sem repetir. Pode completar o prognóstico pouco a pouco.', positionLabel: 'Lugar {position}', emptyOption: 'Selecionar país', saveStatus: 'Estado', saved: 'Guardado neste dispositivo', shareTitle: 'Partilhar prognóstico', shareCopy: 'Gere uma ligação com o prognóstico ou copie um resumo acessível.', copySummary: 'Copiar resumo', copyLink: 'Copiar ligação', reset: 'Reiniciar prognóstico', missingWinner: 'Escolha um vencedor para completar o prognóstico.', missingTop: 'Adicione pelo menos um país ao top 10.', readyTitle: 'Prognóstico pronto', readyCopy: 'O seu prognóstico está guardado e pronto para partilhar.', summaryTitle: 'O meu prognóstico da Eurovisão 2026', winnerSummary: 'Vencedor: {country}', topSummary: 'Top 10:', copied: 'Resumo copiado para a área de transferência.', linkCopied: 'Ligação copiada para a área de transferência.', resetDone: 'Prognóstico reiniciado.', resetConfirm: 'Tem a certeza de que quer apagar o prognóstico?', flagAlt: 'Bandeira de {country}', viewCountry: 'Ver ficha de {country}' },
  ca: { title: 'Quiniela Eurovisió 2026', description: 'Crea i comparteix la teva predicció d’Eurovisió 2026 amb guanyador i top 10 desats en aquest dispositiu.', eyebrow: 'Quiniela Eurovisió 2026', heading: 'Prediu guanyador i top 10', copy: 'Tria el guanyador i ordena el teu top 10. La quiniela es desa en localStorage i es pot compartir amb enllaç o resum accessible.', winnerTitle: 'Guanyador previst', winnerLabel: 'País guanyador', topTitle: 'Top 10 previst', topCopy: 'Selecciona països sense repetir. Pots completar la quiniela a poc a poc.', positionLabel: 'Posició {position}', emptyOption: 'Selecciona un país', saveStatus: 'Estat', saved: 'Desat en aquest dispositiu', shareTitle: 'Compartir quiniela', shareCopy: 'Genera un enllaç amb la predicció o copia un resum accessible.', copySummary: 'Copiar resum', copyLink: 'Copiar enllaç', reset: 'Reiniciar quiniela', missingWinner: 'Tria un guanyador per completar la quiniela.', missingTop: 'Afegeix almenys un país al top 10.', readyTitle: 'Quiniela preparada', readyCopy: 'La predicció està desada i preparada per compartir.', summaryTitle: 'La meva quiniela d’Eurovisió 2026', winnerSummary: 'Guanyador: {country}', topSummary: 'Top 10:', copied: 'Resum copiat al porta-retalls.', linkCopied: 'Enllaç copiat al porta-retalls.', resetDone: 'Quiniela reiniciada.', resetConfirm: 'Segur que vols esborrar la quiniela?', flagAlt: 'Bandera de {country}', viewCountry: 'Veure fitxa de {country}' },
  eu: { title: 'Eurovision 2026 kiniela', description: 'Sortu eta partekatu Eurovision 2026rako iragarpena, irabazlea eta top 10a gailu honetan gordeta.', eyebrow: 'Eurovision 2026 kiniela', heading: 'Iragarri irabazlea eta top 10a', copy: 'Aukeratu irabazlea eta ordenatu zure top 10a. Kiniela localStorage-n gordetzen da eta esteka edo laburpen irisgarriarekin parteka daiteke.', winnerTitle: 'Aurreikusitako irabazlea', winnerLabel: 'Herrialde irabazlea', topTitle: 'Aurreikusitako top 10a', topCopy: 'Aukeratu herrialdeak errepikatu gabe. Kiniela pixkanaka osa dezakezu.', positionLabel: '{position}. postua', emptyOption: 'Aukeratu herrialde bat', saveStatus: 'Egoera', saved: 'Gailu honetan gordeta', shareTitle: 'Partekatu kiniela', shareCopy: 'Sortu esteka iragarpenarekin edo kopiatu laburpen irisgarria.', copySummary: 'Kopiatu laburpena', copyLink: 'Kopiatu esteka', reset: 'Berrabiarazi kiniela', missingWinner: 'Aukeratu irabazle bat kiniela osatzeko.', missingTop: 'Gehitu gutxienez herrialde bat top 10era.', readyTitle: 'Kiniela prest', readyCopy: 'Zure iragarpena gordeta dago eta partekatzeko prest.', summaryTitle: 'Nire Eurovision 2026 kiniela', winnerSummary: 'Irabazlea: {country}', topSummary: 'Top 10a:', copied: 'Laburpena arbelean kopiatu da.', linkCopied: 'Esteka arbelean kopiatu da.', resetDone: 'Kiniela berrabiarazi da.', resetConfirm: 'Ziur kiniela ezabatu nahi duzula?', flagAlt: '{country} herrialdearen bandera', viewCountry: 'Ikusi {country} fitxa' },
  gl: { title: 'Quiniela Eurovisión 2026', description: 'Crea e comparte a túa predición para Eurovisión 2026 con gañador e top 10 gardados neste dispositivo.', eyebrow: 'Quiniela Eurovisión 2026', heading: 'Predí gañador e top 10', copy: 'Escolle o gañador e ordena o teu top 10 persoal. A quiniela gárdase en localStorage e pódese compartir por ligazón ou resumo accesible.', winnerTitle: 'Gañador previsto', winnerLabel: 'País gañador', topTitle: 'Top 10 previsto', topCopy: 'Selecciona países sen repetir. Podes completar a quiniela pouco a pouco.', positionLabel: 'Posto {position}', emptyOption: 'Selecciona un país', saveStatus: 'Estado', saved: 'Gardado neste dispositivo', shareTitle: 'Compartir quiniela', shareCopy: 'Xera unha ligazón coa túa predición ou copia un resumo accesible.', copySummary: 'Copiar resumo', copyLink: 'Copiar ligazón', reset: 'Reiniciar quiniela', missingWinner: 'Escolle un gañador para completar a quiniela.', missingTop: 'Engade polo menos un país ao top 10.', readyTitle: 'Quiniela lista', readyCopy: 'A túa predición está gardada e preparada para compartir.', summaryTitle: 'A miña quiniela de Eurovisión 2026', winnerSummary: 'Gañador: {country}', topSummary: 'Top 10:', copied: 'Resumo copiado no portapapeis.', linkCopied: 'Ligazón copiada no portapapeis.', resetDone: 'Quiniela reiniciada.', resetConfirm: 'Seguro que queres borrar a quiniela?', flagAlt: 'Bandeira de {country}', viewCountry: 'Ver ficha de {country}' },
};

export function getPredictionLabels(locale: Locale) {
  return predictionLabels[locale] ?? predictionLabels.es;
}
