import { defaultLocale, type Locale } from '../config/site';
import type { TimelineMilestoneType } from '../data/eurovisionTimelineMilestones';

type TimelineLabels = {
  title: string; description: string; eyebrow: string; intro: string; filtersTitle: string;
  decade: string; hostCountry: string; winner: string; milestoneType: string;
  allDecades: string; allHosts: string; allWinners: string; allTypes: string; reset: string;
  resultsStatus: string; emptyTitle: string; emptyDescription: string; participants: string;
  host: string; venue: string; winnerLabel: string; milestones: string; edition: string;
  viewEdition: string; viewHostCountry: string; viewWinnerCountry: string; relatedTitle: string;
  rankingsLink: string; countriesLink: string; comparatorLink: string; glossaryTitle: string;
  glossaryIntro: string; dataLimitTitle: string; dataLimit: string;
};

const labels: Record<Locale, TimelineLabels> = {
  es: { title: 'Línea temporal de Eurovision', description: 'Línea temporal interactiva de Eurovision con ediciones, sedes, ganadores, participantes e hitos históricos filtrables.', eyebrow: 'Histórico interactivo', intro: 'Explora el festival año a año con datos del histórico disponible y algunos hitos editoriales configurados. Los filtros no inventan datos: solo actúan sobre ediciones e hitos presentes en la fuente.', filtersTitle: 'Filtrar la línea temporal', decade: 'Década', hostCountry: 'País anfitrión', winner: 'Ganador', milestoneType: 'Tipo de hito', allDecades: 'Todas las décadas', allHosts: 'Todos los anfitriones', allWinners: 'Todos los ganadores', allTypes: 'Todos los tipos', reset: 'Reiniciar filtros', resultsStatus: '{count} hitos visibles', emptyTitle: 'No hay resultados con estos filtros', emptyDescription: 'Prueba a cambiar la década, el país anfitrión, el ganador o el tipo de hito.', participants: 'Participantes', host: 'Anfitrión', venue: 'Sede', winnerLabel: 'Ganador', milestones: 'Hitos', edition: 'Edición', viewEdition: 'Ver edición', viewHostCountry: 'Ver país anfitrión', viewWinnerCountry: 'Ver país ganador', relatedTitle: 'Seguir explorando', rankingsLink: 'Rankings históricos', countriesLink: 'Países', comparatorLink: 'Comparador de países', glossaryTitle: 'Glosario de tipos de hito', glossaryIntro: 'Estos tipos ayudan a filtrar cambios editoriales configurados junto a las ediciones del dataset.', dataLimitTitle: 'Límites de los datos', dataLimit: 'La línea temporal se genera con el dataset histórico disponible. Si una edición no incluye sede, ganador o puntos, la tarjeta lo omite en lugar de inventarlo.' },
  en: { title: 'Eurovision timeline', description: 'Interactive Eurovision timeline with editions, hosts, winners, participants and filterable historical milestones.', eyebrow: 'Interactive history', intro: 'Explore the contest year by year with the available historical data and a small set of configured editorial milestones. Filters do not invent data: they only use editions and milestones present in the source.', filtersTitle: 'Filter the timeline', decade: 'Decade', hostCountry: 'Host country', winner: 'Winner', milestoneType: 'Milestone type', allDecades: 'All decades', allHosts: 'All hosts', allWinners: 'All winners', allTypes: 'All types', reset: 'Reset filters', resultsStatus: '{count} visible milestones', emptyTitle: 'No results with these filters', emptyDescription: 'Try changing the decade, host country, winner or milestone type.', participants: 'Participants', host: 'Host', venue: 'Venue', winnerLabel: 'Winner', milestones: 'Milestones', edition: 'Edition', viewEdition: 'View edition', viewHostCountry: 'View host country', viewWinnerCountry: 'View winning country', relatedTitle: 'Keep exploring', rankingsLink: 'Historical rankings', countriesLink: 'Countries', comparatorLink: 'Country comparator', glossaryTitle: 'Milestone type glossary', glossaryIntro: 'These types help filter configured editorial changes alongside dataset editions.', dataLimitTitle: 'Data limits', dataLimit: 'The timeline is generated from the available historical dataset. If an edition has no venue, winner or points, the card omits it instead of inventing it.' },
  fr: { title: 'Chronologie de l’Eurovision', description: 'Chronologie interactive de l’Eurovision avec éditions, hôtes, gagnants, participants et jalons historiques filtrables.', eyebrow: 'Historique interactif', intro: 'Explorez le concours année par année avec les données historiques disponibles et quelques jalons éditoriaux configurés. Les filtres n’inventent rien : ils utilisent seulement les éditions et jalons présents dans la source.', filtersTitle: 'Filtrer la chronologie', decade: 'Décennie', hostCountry: 'Pays hôte', winner: 'Gagnant', milestoneType: 'Type de jalon', allDecades: 'Toutes les décennies', allHosts: 'Tous les hôtes', allWinners: 'Tous les gagnants', allTypes: 'Tous les types', reset: 'Réinitialiser les filtres', resultsStatus: '{count} jalons visibles', emptyTitle: 'Aucun résultat avec ces filtres', emptyDescription: 'Essayez de changer la décennie, le pays hôte, le gagnant ou le type de jalon.', participants: 'Participants', host: 'Hôte', venue: 'Lieu', winnerLabel: 'Gagnant', milestones: 'Jalons', edition: 'Édition', viewEdition: 'Voir l’édition', viewHostCountry: 'Voir le pays hôte', viewWinnerCountry: 'Voir le pays gagnant', relatedTitle: 'Continuer l’exploration', rankingsLink: 'Classements historiques', countriesLink: 'Pays', comparatorLink: 'Comparateur de pays', glossaryTitle: 'Glossaire des types de jalons', glossaryIntro: 'Ces types aident à filtrer les changements éditoriaux configurés avec les éditions du dataset.', dataLimitTitle: 'Limites des données', dataLimit: 'La chronologie est générée avec le dataset historique disponible. Si une édition n’a pas de lieu, de gagnant ou de points, la carte l’omet au lieu de l’inventer.' },
  pt: { title: 'Linha temporal da Eurovisão', description: 'Linha temporal interativa da Eurovisão com edições, anfitriões, vencedores, participantes e marcos históricos filtráveis.', eyebrow: 'Histórico interativo', intro: 'Explore o festival ano a ano com os dados históricos disponíveis e alguns marcos editoriais configurados. Os filtros não inventam dados: usam apenas edições e marcos presentes na fonte.', filtersTitle: 'Filtrar a linha temporal', decade: 'Década', hostCountry: 'País anfitrião', winner: 'Vencedor', milestoneType: 'Tipo de marco', allDecades: 'Todas as décadas', allHosts: 'Todos os anfitriões', allWinners: 'Todos os vencedores', allTypes: 'Todos os tipos', reset: 'Reiniciar filtros', resultsStatus: '{count} marcos visíveis', emptyTitle: 'Não há resultados com estes filtros', emptyDescription: 'Experimente mudar a década, o país anfitrião, o vencedor ou o tipo de marco.', participants: 'Participantes', host: 'Anfitrião', venue: 'Sede', winnerLabel: 'Vencedor', milestones: 'Marcos', edition: 'Edição', viewEdition: 'Ver edição', viewHostCountry: 'Ver país anfitrião', viewWinnerCountry: 'Ver país vencedor', relatedTitle: 'Continuar a explorar', rankingsLink: 'Rankings históricos', countriesLink: 'Países', comparatorLink: 'Comparador de países', glossaryTitle: 'Glossário de tipos de marco', glossaryIntro: 'Estes tipos ajudam a filtrar mudanças editoriais configuradas juntamente com as edições do dataset.', dataLimitTitle: 'Limites dos dados', dataLimit: 'A linha temporal é gerada com o dataset histórico disponível. Se uma edição não tiver sede, vencedor ou pontos, o cartão omite essa informação em vez de a inventar.' },
  ca: { title: 'Línia temporal d’Eurovisió', description: 'Línia temporal interactiva d’Eurovisió amb edicions, amfitrions, guanyadors, participants i fites històriques filtrables.', eyebrow: 'Històric interactiu', intro: 'Explora el festival any a any amb les dades històriques disponibles i algunes fites editorials configurades. Els filtres no inventen dades: només actuen sobre edicions i fites presents a la font.', filtersTitle: 'Filtrar la línia temporal', decade: 'Dècada', hostCountry: 'País amfitrió', winner: 'Guanyador', milestoneType: 'Tipus de fita', allDecades: 'Totes les dècades', allHosts: 'Tots els amfitrions', allWinners: 'Tots els guanyadors', allTypes: 'Tots els tipus', reset: 'Reiniciar filtres', resultsStatus: '{count} fites visibles', emptyTitle: 'No hi ha resultats amb aquests filtres', emptyDescription: 'Prova de canviar la dècada, el país amfitrió, el guanyador o el tipus de fita.', participants: 'Participants', host: 'Amfitrió', venue: 'Seu', winnerLabel: 'Guanyador', milestones: 'Fites', edition: 'Edició', viewEdition: 'Veure edició', viewHostCountry: 'Veure país amfitrió', viewWinnerCountry: 'Veure país guanyador', relatedTitle: 'Continuar explorant', rankingsLink: 'Rànquings històrics', countriesLink: 'Països', comparatorLink: 'Comparador de països', glossaryTitle: 'Glossari de tipus de fita', glossaryIntro: 'Aquests tipus ajuden a filtrar canvis editorials configurats juntament amb les edicions del dataset.', dataLimitTitle: 'Límits de les dades', dataLimit: 'La línia temporal es genera amb el dataset històric disponible. Si una edició no inclou seu, guanyador o punts, la targeta ho omet en lloc d’inventar-ho.' },
  eu: { title: 'Eurovisioneko denbora-lerroa', description: 'Eurovisioneko denbora-lerro interaktiboa: edizioak, anfitrioiak, irabazleak, parte-hartzaileak eta iragaz daitezkeen mugarri historikoak.', eyebrow: 'Historia interaktiboa', intro: 'Arakatu jaialdia urtez urte datu historiko erabilgarriekin eta konfiguratutako mugarri editorial batzuekin. Iragazkiek ez dute daturik asmatzen: iturrian dauden edizio eta mugarriak bakarrik erabiltzen dituzte.', filtersTitle: 'Iragazi denbora-lerroa', decade: 'Hamarkada', hostCountry: 'Herrialde anfitrioia', winner: 'Irabazlea', milestoneType: 'Mugarri mota', allDecades: 'Hamarkada guztiak', allHosts: 'Anfitrioi guztiak', allWinners: 'Irabazle guztiak', allTypes: 'Mota guztiak', reset: 'Berrezarri iragazkiak', resultsStatus: '{count} mugarri ikusgai', emptyTitle: 'Ez dago emaitzarik iragazki horiekin', emptyDescription: 'Saiatu hamarkada, herrialde anfitrioia, irabazlea edo mugarri mota aldatzen.', participants: 'Parte-hartzaileak', host: 'Anfitrioia', venue: 'Egoitza', winnerLabel: 'Irabazlea', milestones: 'Mugarriak', edition: 'Edizioa', viewEdition: 'Ikusi edizioa', viewHostCountry: 'Ikusi herrialde anfitrioia', viewWinnerCountry: 'Ikusi herrialde irabazlea', relatedTitle: 'Jarraitu arakatzen', rankingsLink: 'Ranking historikoak', countriesLink: 'Herrialdeak', comparatorLink: 'Herrialdeen konparatzailea', glossaryTitle: 'Mugarri moten glosarioa', glossaryIntro: 'Mota hauek konfiguratutako aldaketa editorialak dataseten edizioekin batera iragazten laguntzen dute.', dataLimitTitle: 'Datuen mugak', dataLimit: 'Denbora-lerroa eskuragarri dagoen dataset historikoarekin sortzen da. Edizio batek egoitza, irabazle edo punturik ez badu, txartelak ez du informazio hori asmatzen.' },
  gl: { title: 'Liña temporal de Eurovisión', description: 'Liña temporal interactiva de Eurovisión con edicións, anfitrións, gañadores, participantes e fitos históricos filtrables.', eyebrow: 'Histórico interactivo', intro: 'Explora o festival ano a ano cos datos históricos dispoñibles e algúns fitos editoriais configurados. Os filtros non inventan datos: só actúan sobre edicións e fitos presentes na fonte.', filtersTitle: 'Filtrar a liña temporal', decade: 'Década', hostCountry: 'País anfitrión', winner: 'Gañador', milestoneType: 'Tipo de fito', allDecades: 'Todas as décadas', allHosts: 'Todos os anfitrións', allWinners: 'Todos os gañadores', allTypes: 'Todos os tipos', reset: 'Reiniciar filtros', resultsStatus: '{count} fitos visibles', emptyTitle: 'Non hai resultados con estes filtros', emptyDescription: 'Proba a cambiar a década, o país anfitrión, o gañador ou o tipo de fito.', participants: 'Participantes', host: 'Anfitrión', venue: 'Sede', winnerLabel: 'Gañador', milestones: 'Fitos', edition: 'Edición', viewEdition: 'Ver edición', viewHostCountry: 'Ver país anfitrión', viewWinnerCountry: 'Ver país gañador', relatedTitle: 'Seguir explorando', rankingsLink: 'Rankings históricos', countriesLink: 'Países', comparatorLink: 'Comparador de países', glossaryTitle: 'Glosario de tipos de fito', glossaryIntro: 'Estes tipos axudan a filtrar cambios editoriais configurados xunto ás edicións do dataset.', dataLimitTitle: 'Límites dos datos', dataLimit: 'A liña temporal xérase co dataset histórico dispoñible. Se unha edición non inclúe sede, gañador ou puntos, a tarxeta omíteo no canto de inventalo.' },
};

export const timelineTypeLabels: Record<Locale, Record<TimelineMilestoneType | 'edition', string>> = {
  es: { edition: 'Edición', contest: 'Festival', format: 'Formato', voting: 'Votación' },
  en: { edition: 'Edition', contest: 'Contest', format: 'Format', voting: 'Voting' },
  fr: { edition: 'Édition', contest: 'Concours', format: 'Format', voting: 'Vote' },
  pt: { edition: 'Edição', contest: 'Festival', format: 'Formato', voting: 'Votação' },
  ca: { edition: 'Edició', contest: 'Festival', format: 'Format', voting: 'Votació' },
  eu: { edition: 'Edizioa', contest: 'Jaialdia', format: 'Formatua', voting: 'Bozketa' },
  gl: { edition: 'Edición', contest: 'Festival', format: 'Formato', voting: 'Votación' },
};

export function getTimelineLabels(locale: Locale = defaultLocale) {
  return labels[locale] ?? labels[defaultLocale];
}

export function getTimelineTypeLabels(locale: Locale = defaultLocale) {
  return timelineTypeLabels[locale] ?? timelineTypeLabels[defaultLocale];
}
